import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react';
import { useForm, SubmitHandler, Controller } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import { formSchema } from '@schemas/form';
import Input from '@components/input';

const Home: NextPage = () => {
  const {
    formState: { errors },
    handleSubmit,
    register,
    watch,
    control,
  } = useForm({
    resolver: yupResolver(formSchema),
    mode: 'onChange',
    reValidateMode: 'onChange',
  });
  const onSubmit = (data: any) => console.log(data);

  console.log(watch("name"));
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Testing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit(onSubmit)} noValidate>
          <Controller
            /* eslint-disable-next-line */
            render={({ field: { ref, ...rest } }) => (
              <Input
                {...rest}
                register={register}
                error={errors.age?.message}
                data-testid="age"
                id="age"
                name="age"
                type="tel"
                required
              />
            )}
            control={control}
            name="age"
            defaultValue=""
          />
          <input type="submit" />
        </form>
      </main>
    </div>
  )
}

export default Home
